### ISSUE TITLE
🚀 Feature: İkili Filtrelemeden Akıllı Puanlama Sistemine Geçiş

### ISSUE THREAD

**Issue by furkan-ucan** [furkan-ucan/ai-career-assistant#1]
## 📋 Özellik Özeti

Mevcut ikili filtreleme sistemini (ilan ya geçer ya kalır) daha gelişmiş bir **ağırlıklandırılmış puanlama sistemine** dönüştürme.

## 🎯 Problem

Şu anki sistem çok katı: tek bir "kırmızı bayrak" kelimesi (örn: "senior") potansiyel olarak uygun bir ilanı eleyebiliyor. Örneğin, "Junior Developer" başlıklı bir ilan, açıklamasında geçen "lead" kelimesi yüzünden direkt eleniyor.

### 1. Ağırlıklandırılmış Puanlama Sistemi
- Her negatif kelime/kriter belirli eksi puan (-5, -10, -50 vb.)
- Her pozitif kelime/kriter belirli artı puan (+10, +40 vb.)
- Toplam puan eşiğin altına düşerse ilan elenir

### 2. Akıllı Deneyim Tespiti
- Mevcut: `["5+ yıl", "5 yıl"]` gibi sabit stringler
- Yeni: `(\d+)\s*(yıl|sene|year)` regex ile dinamik tespit

### 3. Performans Optimizasyonu
- Regex pattern'lerini program başında bir kez derleme
- Her fonksiyon çağrısında yeniden derleme yerine

### Puanlama Örnekleri:
```yaml
title_weights:
  "senior": -50      # Çok güçlü negatif
  "junior": +40      # Güçlü pozitif
  "manager": -30     # Orta negatif

experience_weights:
  "5+ yıl": -20      # Regex ile yakalanacak
  "yeni mezun": +30  # Pozitif sinyal
```

### Eşik Örneği:
- Toplam puan < -20 → İlan elenir
- Toplam puan ≥ -20 → İlan geçer

## ✅ Kabul Kriterleri

- [ ] Puanlama sistemi config.yaml'da tanımlanabilir
- [ ] Regex ile deneyim yılı tespiti çalışır
- [ ] Performans testleri geçer
- [ ] Eski filtreleme sistemi ile sonuçlar karşılaştırılır
- [ ] Debug modu detaylı puanlama raporu verir

## 🔄 Aşamalar

1. **Hafta 1**: Temel puanlama altyapısı
2. **Hafta 2**: Regex deneyim tespiti
3. **Hafta 3**: Performans optimizasyonu
4. **Hafta 4**: Test ve kalibre etme

## 📊 Beklenen Sonuç

- %15-20 daha fazla uygun ilan bulma
- Yanlış negatif oranında azalma
- Daha esnek ve konfigüre edilebilir sistem

## 🔗 İlgili Dosyalar

- `src/filter.py` - Ana filtreleme modülü
- `config.yaml` - Puanlama ağırlıkları
- `tests/test_scoring.py` - Yeni test dosyası
